const DEMO_LOCATION = { lat: 35.681236, lng: 139.767125, accuracy: 8 };
const STORAGE_KEY = 'navi-scope-spots';
const $ = (selector) => document.querySelector(selector);
const state = { spots: [], position: null, rawHeading: 0, heading: 0, offset: 0, demo: false, permissionStep: 0, stream: null, map: null, marker: null, locationMarker: null, locationAccuracy: null, headingLine: null, editingId: null, watchId: null };
const panorama = { yaw: 0, dragging: false, lastX: 0, texture: null, orientationEnabled: false };

const permissionSteps = [
  { title: 'GPS を許可', description: '現在地を使って周囲の建物を計算します' },
  { title: 'ジャイロを許可', description: '端末の向きとコンパスを取得します' },
  { title: 'カメラを起動', description: '背面カメラに案内情報を重ねます' },
  { title: '準備完了', description: '端末を周囲へ向けてスポットを探せます' }
];

function loadSpots() {
  try { state.spots = JSON.parse(localStorage.getItem(STORAGE_KEY) || '[]'); } catch { state.spots = []; }
  if (!state.spots.length) state.spots = [{ id: 1700000000000, name: '東京駅 丸の内駅舎', lat: 35.681236, lng: 139.767125, desc: '赤レンガが印象的な東京駅の象徴的な駅舎です。' }, { id: 1700000000001, name: 'KITTE 丸の内', lat: 35.68018, lng: 139.76682, desc: '旧東京中央郵便局を活用した商業施設です。' }];
  saveSpots();
}
function saveSpots() { localStorage.setItem(STORAGE_KEY, JSON.stringify(state.spots)); }
function showToast(message) { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); clearTimeout(showToast.timer); showToast.timer = setTimeout(() => toast.classList.remove('show'), 2400); }
function formatDistance(meters) { return meters < 1000 ? `${Math.round(meters)} m` : `${(meters / 1000).toFixed(2)} km`; }
function toRad(value) { return value * Math.PI / 180; }
function toDeg(value) { return value * 180 / Math.PI; }
function distanceBetween(a, b) { const earth = 6371000; const dLat = toRad(b.lat - a.lat); const dLng = toRad(b.lng - a.lng); const x = Math.sin(dLat / 2) ** 2 + Math.cos(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.sin(dLng / 2) ** 2; return earth * 2 * Math.atan2(Math.sqrt(x), Math.sqrt(1 - x)); }
function bearingBetween(a, b) { const dLng = toRad(b.lng - a.lng); const y = Math.sin(dLng) * Math.cos(toRad(b.lat)); const x = Math.cos(toRad(a.lat)) * Math.sin(toRad(b.lat)) - Math.sin(toRad(a.lat)) * Math.cos(toRad(b.lat)) * Math.cos(dLng); return (toDeg(Math.atan2(y, x)) + 360) % 360; }
function angleDifference(angle) { return (angle + 540) % 360 - 180; }

function updatePermissionPanel() { const step = permissionSteps[state.permissionStep]; $('#permissionStep').textContent = String(Math.min(state.permissionStep + 1, 4)).padStart(2, '0'); $('#permissionTitle').textContent = step.title; $('#permissionDescription').textContent = step.description; $('#permissionButton').textContent = state.permissionStep >= 3 ? '再確認' : '許可する'; if (state.permissionStep >= 3) $('#permissionPanel').classList.add('complete'); }
async function requestPermissionStep() {
  try {
    if (state.permissionStep === 0) { if (!state.demo && navigator.geolocation) await new Promise((resolve) => navigator.geolocation.getCurrentPosition((position) => { setPosition(position.coords.latitude, position.coords.longitude, position.coords.accuracy); showToast(`GPS を取得しました（精度 ±${Math.round(position.coords.accuracy)}m）`); resolve(); }, (error) => { const messages = { 1: '位置情報の権限が拒否されています', 2: '位置情報を取得できませんでした', 3: '位置情報の取得がタイムアウトしました' }; state.demo = true; setPosition(DEMO_LOCATION.lat, DEMO_LOCATION.lng, DEMO_LOCATION.accuracy); showToast(`${messages[error.code] || 'GPS を取得できませんでした'}。デモモードへ切り替えます`); resolve(); }, { enableHighAccuracy: true, maximumAge: 0, timeout: 15000 })); else { state.demo = true; setPosition(DEMO_LOCATION.lat, DEMO_LOCATION.lng, DEMO_LOCATION.accuracy); showToast('GPS が利用できないためデモモードを使用します'); } state.permissionStep = 1; startLocationWatch(); }
    else if (state.permissionStep === 1) { if (typeof DeviceOrientationEvent !== 'undefined' && typeof DeviceOrientationEvent.requestPermission === 'function') { const result = await DeviceOrientationEvent.requestPermission(); if (result !== 'granted') showToast('ジャイロ権限が許可されませんでした'); } window.addEventListener('deviceorientationabsolute', handleOrientation, true); window.addEventListener('deviceorientation', handleOrientation, true); state.permissionStep = 2; }
    else if (state.permissionStep === 2) { await startCamera(); state.permissionStep = 3; }
    else { showToast('すべてのセンサーが準備できています'); }
  } catch (error) { showToast('権限の取得に失敗しました。HTTPS または localhost を確認してください'); }
  updatePermissionPanel();
}
function startLocationWatch() { if (!navigator.geolocation || state.watchId !== null || state.demo) return; state.watchId = navigator.geolocation.watchPosition((position) => setPosition(position.coords.latitude, position.coords.longitude, position.coords.accuracy), () => showToast('GPS 更新を停止しました'), { enableHighAccuracy: true, maximumAge: 1500, timeout: 10000 }); }
function setPosition(lat, lng, accuracy) { state.position = { lat, lng, accuracy }; updateHud(); updateMapLocationOverlay(); renderAr(); if (state.map && !state.marker) state.map.setView([lat, lng], 17); }
function handleOrientation(event) { let nextHeading; if (typeof event.webkitCompassHeading === 'number') nextHeading = event.webkitCompassHeading; else if (typeof event.alpha === 'number') nextHeading = 360 - event.alpha; if (typeof nextHeading === 'number' && Number.isFinite(nextHeading)) { state.rawHeading = nextHeading; state.heading = (state.rawHeading + state.offset + 360) % 360; updateHud(); updateMapLocationOverlay(); renderAr(); } }
async function startCamera() { if (!navigator.mediaDevices?.getUserMedia) throw new Error('unsupported'); state.stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: { ideal: 'environment' } }, audio: false }); $('#camera').srcObject = state.stream; $('#cameraFallback').style.display = 'none'; $('#headerStatus').innerHTML = '<span class="status-dot"></span><span>LIVE</span>'; }
function updateHud() { const position = state.position; $('#hudCoordinates').textContent = position ? `${position.lat.toFixed(5)} / ${position.lng.toFixed(5)}` : 'デモモード'; $('#hudAccuracy').textContent = position ? `±${Math.round(position.accuracy)} m` : '-- m'; $('#hudHeading').textContent = `${Math.round(state.heading)}°`; }
function renderAr() { if (!state.position) return; const layer = $('#arLayer'); const visible = []; state.spots.forEach((spot) => { const distance = distanceBetween(state.position, spot); const bearing = bearingBetween(state.position, spot); const relative = angleDifference(bearing - state.heading); if (Math.abs(relative) <= 48) visible.push({ spot, distance, bearing, relative }); }); visible.sort((a, b) => a.distance - b.distance); layer.innerHTML = visible.map(({ spot, distance, bearing, relative }, index) => { const left = Math.max(10, Math.min(90, 50 + relative / 60 * 50)); const top = 29 + Math.min(index * 7, 28); const scale = (1.06 - Math.min(index, 4) * .04).toFixed(2); return `<button class="ar-card" style="left:${left}%; top:${top}%; z-index:${1000 - index}; --card-scale:${scale}" data-spot-id="${spot.id}"><h3>${escapeHtml(spot.name)}</h3><p>${formatDistance(distance)} / ${Math.round(bearing)}°</p><p class="bearing-line">タップして詳細を見る</p></button>`; }).join(''); $('#hudVisible').textContent = `${visible.length} SPOTS`; $('#spotCount').textContent = visible.length; layer.querySelectorAll('.ar-card').forEach((card) => card.addEventListener('click', () => openSpotDialog(Number(card.dataset.spotId)))); }
function escapeHtml(value) { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char])); }
function openSpotDialog(id) { const spot = state.spots.find((item) => item.id === id); if (!spot) return; $('#dialogName').textContent = spot.name; $('#dialogDistance').textContent = state.position ? formatDistance(distanceBetween(state.position, spot)) : '距離を計算中'; $('#dialogDescription').textContent = spot.desc || '説明は登録されていません。'; $('#spotDialog').showModal(); }

function createPanoramaTexture() { const texture = document.createElement('canvas'); texture.width = 2400; texture.height = 700; const context = texture.getContext('2d'); const sky = context.createLinearGradient(0, 0, 0, 700); sky.addColorStop(0, '#173f49'); sky.addColorStop(.55, '#68a9a0'); sky.addColorStop(.56, '#8aa18c'); sky.addColorStop(1, '#263f37'); context.fillStyle = sky; context.fillRect(0, 0, texture.width, texture.height); context.fillStyle = 'rgba(255,246,190,.85)'; context.beginPath(); context.arc(510, 125, 55, 0, Math.PI * 2); context.fill(); for (let index = 0; index < 18; index += 1) { const x = index * 137 - 24; const width = 80 + (index % 4) * 24; const height = 110 + (index % 5) * 45; const top = 480 - height; context.fillStyle = index % 3 === 0 ? '#203b3a' : '#34534d'; context.fillRect(x, top, width, height); context.fillStyle = 'rgba(244,201,93,.65)'; for (let row = 0; row < 4; row += 1) for (let column = 0; column < 3; column += 1) context.fillRect(x + 15 + column * 20, top + 18 + row * 25, 8, 10); } context.fillStyle = '#152723'; context.fillRect(0, 480, texture.width, 220); context.strokeStyle = 'rgba(85,214,187,.32)'; context.lineWidth = 2; for (let x = -500; x < texture.width + 500; x += 170) { context.beginPath(); context.moveTo(texture.width / 2, 480); context.lineTo(x, 700); context.stroke(); } context.fillStyle = 'rgba(237,246,242,.75)'; context.font = '600 26px DM Sans'; for (let index = 0; index < 6; index += 1) context.fillText(['NORTH QUAD', 'LIBRARY', 'MAIN GATE', 'LAB WING', 'CAFETERIA', 'TOWER'][index], index * 400 + 35, 430 - (index % 2) * 30); return texture; }
function renderPanorama() { const canvas = $('#panoramaCanvas'); if (!canvas) return; const bounds = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; const width = Math.max(1, Math.round(bounds.width * ratio)); const height = Math.max(1, Math.round(bounds.height * ratio)); if (canvas.width !== width || canvas.height !== height) { canvas.width = width; canvas.height = height; } if (!panorama.texture) panorama.texture = createPanoramaTexture(); const context = canvas.getContext('2d'); const scale = height / panorama.texture.height; const panoramaWidth = panorama.texture.width * scale; const offset = ((panorama.yaw % 360) + 360) % 360 / 360 * panoramaWidth; context.clearRect(0, 0, width, height); context.save(); context.translate(-offset, 0); context.drawImage(panorama.texture, 0, 0, panoramaWidth, height); context.drawImage(panorama.texture, panoramaWidth, 0, panoramaWidth, height); context.restore(); $('#panoramaHeading').textContent = `方位 ${Math.round(((panorama.yaw % 360) + 360) % 360)}°`; }
function openPanorama() { $('#panoramaDialog').showModal(); requestAnimationFrame(renderPanorama); }
function handlePanoramaOrientation(event) { let nextHeading; if (typeof event.webkitCompassHeading === 'number') nextHeading = event.webkitCompassHeading; else if (typeof event.alpha === 'number') nextHeading = 360 - event.alpha; if (typeof nextHeading === 'number' && Number.isFinite(nextHeading)) { panorama.yaw = nextHeading; renderPanorama(); } }
async function enablePanoramaOrientation() { try { if (typeof DeviceOrientationEvent !== 'undefined' && typeof DeviceOrientationEvent.requestPermission === 'function') { const result = await DeviceOrientationEvent.requestPermission(); if (result !== 'granted') return showToast('端末の向きが許可されませんでした'); } if (!panorama.orientationEnabled) { window.addEventListener('deviceorientationabsolute', handlePanoramaOrientation, true); window.addEventListener('deviceorientation', handlePanoramaOrientation, true); panorama.orientationEnabled = true; } showToast('端末の向きで360°ビューを操作します'); } catch { showToast('端末の向きを利用できません'); } }
function wirePanoramaEvents() { $('#openPanorama').addEventListener('click', openPanorama); $('#closePanorama').addEventListener('click', () => $('#panoramaDialog').close()); $('#enablePanoramaOrientation').addEventListener('click', enablePanoramaOrientation); const canvas = $('#panoramaCanvas'); canvas.addEventListener('pointerdown', (event) => { panorama.dragging = true; panorama.lastX = event.clientX; canvas.setPointerCapture(event.pointerId); }); canvas.addEventListener('pointermove', (event) => { if (!panorama.dragging) return; panorama.yaw -= (event.clientX - panorama.lastX) * .18; panorama.lastX = event.clientX; renderPanorama(); }); canvas.addEventListener('pointerup', () => { panorama.dragging = false; }); canvas.addEventListener('pointercancel', () => { panorama.dragging = false; }); window.addEventListener('resize', () => { if ($('#panoramaDialog').open) renderPanorama(); }); }

function updateMapLocationOverlay() { if (!state.map || !state.position || typeof L === 'undefined') return; const { lat, lng, accuracy } = state.position; const point = [lat, lng]; if (!state.locationMarker) { state.locationMarker = L.marker(point, { icon: L.divIcon({ className: 'current-location-pin', html: '<span></span>', iconSize: [22, 22], iconAnchor: [11, 11] }), keyboard: false, zIndexOffset: 1000 }).addTo(state.map).bindTooltip('現在地'); state.locationAccuracy = L.circle(point, { color: '#55d6bb', fillColor: '#55d6bb', fillOpacity: .1, weight: 1, interactive: false }).addTo(state.map); state.headingLine = L.polyline([point, point], { color: '#f4c95d', weight: 3, opacity: .9, interactive: false }).addTo(state.map); } else { state.locationMarker.setLatLng(point); state.locationAccuracy.setLatLng(point); } state.locationAccuracy.setRadius(Math.max(Number(accuracy) || 10, 10)); const headingDistance = 45; const headingPoint = [lat + Math.cos(toRad(state.heading)) * headingDistance / 111320, lng + Math.sin(toRad(state.heading)) * headingDistance / (111320 * Math.cos(toRad(lat)))]; state.headingLine.setLatLngs([point, headingPoint]); }
function initializeMap() { if (state.map || typeof L === 'undefined') return; const start = state.position || DEMO_LOCATION; state.map = L.map('map', { zoomControl: false }).setView([start.lat, start.lng], 16); L.control.zoom({ position: 'bottomright' }).addTo(state.map); L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 19, attribution: '&copy; OpenStreetMap contributors' }).addTo(state.map); state.map.on('click', (event) => { state.editingId = null; $('#editorTitle').textContent = '新しいスポット'; setEditorCoordinates(event.latlng.lat, event.latlng.lng); placeEditorMarker(event.latlng.lat, event.latlng.lng); }); renderMapMarkers(); updateMapLocationOverlay(); }
function renderMapMarkers() { if (!state.map) return; if (state.marker) { state.map.removeLayer(state.marker); state.marker = null; } state.map.eachLayer((layer) => { if (layer instanceof L.Marker && layer !== state.locationMarker) state.map.removeLayer(layer); }); state.spots.forEach((spot) => { const marker = L.marker([spot.lat, spot.lng], { draggable: true }).addTo(state.map).bindPopup(`<strong>${escapeHtml(spot.name)}</strong>`); marker.on('click', () => editSpot(spot.id)); marker.on('dragend', (event) => { const point = event.target.getLatLng(); setEditorCoordinates(point.lat, point.lng); state.editingId = spot.id; $('#editorTitle').textContent = 'スポットを編集'; }); }); }
function placeEditorMarker(lat, lng) { if (!state.map) return; if (state.marker) state.map.removeLayer(state.marker); state.marker = L.marker([lat, lng], { draggable: true, opacity: .86 }).addTo(state.map).bindTooltip('新しいピン', { direction: 'top', offset: [0, -12] }).openTooltip(); state.marker.on('dragend', (event) => { const point = event.target.getLatLng(); setEditorCoordinates(point.lat, point.lng); }); }
function setEditorCoordinates(lat, lng) { $('#spotLat').value = lat.toFixed(6); $('#spotLng').value = lng.toFixed(6); $('#pinStatus').textContent = '座標を選択済み'; }
function editSpot(id) { const spot = state.spots.find((item) => item.id === id); if (!spot) return; state.editingId = id; $('#editorTitle').textContent = 'スポットを編集'; $('#spotName').value = spot.name; $('#spotLat').value = spot.lat; $('#spotLng').value = spot.lng; $('#spotDesc').value = spot.desc || ''; setEditorCoordinates(spot.lat, spot.lng); }
function clearForm() { state.editingId = null; $('#editorTitle').textContent = '新しいスポット'; $('#spotForm').reset(); $('#spotName').value = ''; $('#spotLat').value = ''; $('#spotLng').value = ''; $('#spotDesc').value = ''; $('#pinStatus').textContent = '地図をタップ'; if (state.marker && state.map) { state.map.removeLayer(state.marker); state.marker = null; } }
function renderSpotList() { $('#listCount').textContent = state.spots.length; $('#spotList').innerHTML = state.spots.length ? state.spots.map((spot) => `<div class="spot-row"><div class="spot-info"><strong>${escapeHtml(spot.name)}</strong><span>${escapeHtml(spot.desc || '説明なし')}</span></div><span class="spot-coords">${Number(spot.lat).toFixed(5)}, ${Number(spot.lng).toFixed(5)}</span><button class="delete-button" type="button" data-delete-id="${spot.id}" aria-label="${escapeHtml(spot.name)}を削除">×</button></div>`).join('') : '<div class="empty-state">登録されたスポットはありません</div>'; $('#spotList').querySelectorAll('[data-delete-id]').forEach((button) => button.addEventListener('click', () => { state.spots = state.spots.filter((spot) => spot.id !== Number(button.dataset.deleteId)); saveSpots(); renderSpotList(); renderMapMarkers(); renderAr(); showToast('スポットを削除しました'); })); }
function generateDemoSpots() { const origin = state.position || DEMO_LOCATION; const names = ['サンプル・ホール', 'リバーサイド研究棟', 'コミュニティラボ']; const descriptions = ['現場テスト用に生成されたスポットです。', '現在地から近い位置にあるデモ建物です。', '案内表示のテストに利用できます。']; state.spots = names.map((name, index) => { const distance = 55 + index * 19; const bearing = [35, 155, 275][index]; const lat = origin.lat + (distance * Math.cos(toRad(bearing))) / 111320; const lng = origin.lng + (distance * Math.sin(toRad(bearing))) / (111320 * Math.cos(toRad(origin.lat))); return { id: Date.now() + index, name, lat, lng, desc: descriptions[index] }; }); saveSpots(); renderSpotList(); renderMapMarkers(); renderAr(); showToast('周辺にデモスポットを生成しました'); }
function exportJson() { const blob = new Blob([JSON.stringify(state.spots, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'buildings.json'; link.click(); URL.revokeObjectURL(link.href); showToast('buildings.json を出力しました'); }
function importJson(event) { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = JSON.parse(reader.result); if (!Array.isArray(imported) || imported.some((spot) => !spot.name || !Number.isFinite(Number(spot.lat)) || !Number.isFinite(Number(spot.lng)))) throw new Error('invalid'); state.spots = imported.map((spot) => ({ id: spot.id || Date.now() + Math.random(), name: String(spot.name), lat: Number(spot.lat), lng: Number(spot.lng), desc: String(spot.desc || '') })); saveSpots(); renderSpotList(); renderMapMarkers(); renderAr(); showToast(`${state.spots.length}件のスポットを読み込みました`); } catch { showToast('JSON の形式が正しくありません'); } event.target.value = ''; }; reader.readAsText(file); }

function switchView(viewId) { document.querySelectorAll('.view').forEach((view) => view.classList.toggle('active-view', view.id === viewId)); document.querySelectorAll('.nav-item').forEach((item) => item.classList.toggle('active', item.dataset.view === viewId)); if (viewId === 'adminView') { initializeMap(); setTimeout(() => state.map?.invalidateSize(), 50); } }
function wireEvents() { $('#permissionButton').addEventListener('click', requestPermissionStep); $('#headingOffset').addEventListener('input', (event) => { state.offset = Number(event.target.value); $('#offsetValue').textContent = `${state.offset > 0 ? '+' : ''}${state.offset}°`; state.heading = (state.rawHeading + state.offset + 360) % 360; updateHud(); renderAr(); }); $('#toggleDemo').addEventListener('click', () => { state.demo = !state.demo; if (state.demo) { setPosition(DEMO_LOCATION.lat, DEMO_LOCATION.lng, DEMO_LOCATION.accuracy); showToast('東京駅周辺のデモモードです'); } else showToast('実 GPS モードに切り替えました'); }); $('#centerView').addEventListener('click', () => { state.rawHeading = 0; state.heading = 0; state.offset = 0; $('#headingOffset').value = 0; $('#offsetValue').textContent = '0°'; updateHud(); renderAr(); }); $('#closeDialog').addEventListener('click', () => $('#spotDialog').close()); $('#spotForm').addEventListener('submit', (event) => { event.preventDefault(); const entry = { id: state.editingId || Date.now(), name: $('#spotName').value.trim(), lat: Number($('#spotLat').value), lng: Number($('#spotLng').value), desc: $('#spotDesc').value.trim() }; if (!entry.name || !Number.isFinite(entry.lat) || !Number.isFinite(entry.lng)) return showToast('建物名と座標を入力してください'); const index = state.spots.findIndex((spot) => spot.id === state.editingId); if (index >= 0) state.spots[index] = entry; else state.spots.push(entry); saveSpots(); renderSpotList(); renderMapMarkers(); renderAr(); clearForm(); showToast('スポットを保存しました'); }); $('#clearForm').addEventListener('click', clearForm); $('#locateButton').addEventListener('click', () => { const position = state.position || DEMO_LOCATION; state.map?.setView([position.lat, position.lng], 18); setEditorCoordinates(position.lat, position.lng); showToast(state.demo ? 'デモ座標へ移動しました' : '現在地へ移動しました'); }); $('#demoSpotsButton').addEventListener('click', generateDemoSpots); $('#exportButton').addEventListener('click', exportJson); $('#importInput').addEventListener('change', importJson); document.querySelectorAll('.nav-item').forEach((item) => item.addEventListener('click', () => switchView(item.dataset.view))); }

loadSpots(); updatePermissionPanel(); updateHud(); renderSpotList(); renderAr(); wireEvents(); wirePanoramaEvents();
